import Head from 'next/head'
import About from './components/About';

import Main from './components/Main';
import Skills from './components/Skills';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Eshant Manghnani Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
    </div>
  )
}
